//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PETool.rc
//
#define IDC_MYICON                      2
#define IDB_DOS_REFRESH                 3
#define IDB_PE_REFRESH                  3
#define IDB_FILE_REFRESH                3
#define IDB_SEC_SAVE                    3
#define IDOK2                           3
#define IDB_TOOL_REMOTE_UNINS           3
#define IDB_EDIT_DIR_EX                 4
#define IDB_SEC_REFRESH                 4
#define IDB_EDIT_DIR_IM                 5
#define IDB_TOOL_REMOTE_OPENDLL         5
#define IDB_EDIT_DIR_RES                6
#define IDB_EDIT_DIR_REL                7
#define IDB_EDIT_DIR_DEB                8
#define IDB_EDIT_DIR_IAT                9
#define IDB_EDIT_DIR_COM                10
#define IDD_PETOOL_DIALOG               102
#define IDD_EDIT_DOS                    102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_PETOOL                      107
#define IDC_PETOOL                      109
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     133
#define IDD_EDIT_PE                     135
#define IDD_EDIT_FILE                   135
#define IDD_EDIT_OPT                    136
#define IDD_EDIT_SECTION                137
#define IDD_EDIT_DIR                    138
#define IDD_EDIT_DIR_EXPORT             139
#define IDD_EDIT_DIR_IMPORT             140
#define IDD_TOOL_CONVERTER              141
#define IDD_TOOL_SECTION                142
#define IDB_BITMAP_PE                   147
#define IDB_BITMAP_OPEN                 151
#define IDI_ICON1                       152
#define IDI_SMALL                       152
#define IDB_BITMAP_SAVE                 155
#define IDB_BITMAP_SECTION              156
#define IDB_BITMAP3                     161
#define IDB_BITMAP_DIR                  164
#define IDB_BITMAP_PRO                  166
#define IDB_BITMAP_IM                   167
#define IDB_BITMAP5                     168
#define IDB_BITMAP_EX                   168
#define IDB_TOOLBAR_OPEN                168
#define IDB_TOOLBAR_PRO                 169
#define IDB_TOOLBAR_SAVE                170
#define IDB_TOOLBAR_DOS                 171
#define IDB_TOOLBAR_PE                  172
#define IDB_TOOLBAR_OPT                 173
#define IDB_TOOLBAR_SEC                 174
#define IDB_TOOLBAR_DIR                 175
#define IDB_TOOLBAR_EX                  176
#define IDB_TOOLBAR_IM                  177
#define IDB_BITMAP_OPT                  177
#define IDD_FILE_PROCESS                178
#define IDD_TOOL_REMOTEINJ              179
#define IDI_ICON2                       180
#define IDI_ICON_KEY                    180
#define IDC_EDIT_DOS_MAGIC              1000
#define IDC_EDIT_DOS_CP                 1001
#define IDC_EDIT_DOS_CBLP               1002
#define IDC_EDIT_DOS_CRIC               1004
#define IDC_EDIT_DOS_CPARHDR            1005
#define IDC_EDIT_DOS_MIN                1006
#define IDC_EDIT_DOS_MAX                1007
#define IDC_EDIT_DOS_SS                 1008
#define IDC_EDIT_DOS_SP                 1009
#define IDC_EDIT_DOS_CSUM               1010
#define IDC_EDIT_DOS_IP                 1011
#define IDC_EDIT_DOS_CS                 1012
#define IDC_EDIT_DOS_LFARLC             1013
#define IDC_EDIT_DOS_OVNO               1014
#define IDC_EDIT_DOS_RES4               1015
#define IDC_EDIT_DOS_OEMID              1016
#define IDC_EDIT_DOS_OEMINFO            1017
#define IDC_EDIT_DOS_RES10              1018
#define IDC_EDIT_DOS_LFANEW             1019
#define IDC_EDIT_OPT_FA                 1019
#define IDB_DOS_SAVE                    1020
#define IDC_EDIT_OPT_HSIZE              1021
#define IDC_EDIT_FILE_MACHINE           1022
#define IDC_EDIT_OPT_IMAGESIZE          1022
#define IDC_EDIT_FILE_SECTIONS          1023
#define IDC_EDIT_FILE_TIME              1024
#define IDC_EDIT_FILE_ST                1025
#define IDC_EDIT_OPT_CHECKSUM           1025
#define IDC_EDIT_FILE_NUMSYM            1026
#define IDC_EDIT_OPT_SUB                1026
#define IDC_EDIT_FILE_SIZEOPT           1027
#define IDC_EDIT_OPT_DLL                1027
#define IDC_EDIT_FILE_CHAR              1028
#define IDC_EDIT_OPT_STACKR             1028
#define IDC_EDIT_OPT_STACKC             1029
#define IDB_PE_SAVE                     1030
#define IDB_FILE_SAVE                   1030
#define IDC_EDIT_OPT_HEAPR              1031
#define IDC_EDIT_OPT_HEAPC              1032
#define IDC_EDIT_OPT_FLAGS              1034
#define IDC_EDIT_DOS_LFANEW5            1035
#define IDC_EDIT_OPT_DIRNUM             1035
#define IDC_EDIT_OPT_MAGIC              1037
#define IDC_EDIT_OPT_ALINDER            1038
#define IDC_EDIT_OPT_ILINKER            1039
#define IDC_EDIT_OPT_SIZECODE           1040
#define IDC_EDIT_OPT_IDATA              1041
#define IDC_EDIT_OPT_UDATA              1042
#define IDC_EDIT_OPT_ENTRY              1043
#define IDC_EDIT_OPT_BASECODE           1044
#define IDC_EDIT_OPT_BASEDATA           1045
#define IDC_EDIT_OPT_IMAGEBASE          1046
#define IDC_EDIT_OPT_SA                 1047
#define IDC_EDIT_OPT_AOSV               1048
#define IDC_EDIT_OPT_IOSV               1049
#define IDC_EDIT_OPT_AIV                1050
#define IDC_EDIT_OPT_IIV                1051
#define IDC_EDIT_OPT_ASV                1052
#define IDC_EDIT_OPT_ISV                1053
#define IDC_EDIT_OPT_WIN32              1054
#define IDB_OPT_SAVE                    1055
#define IDB_OPT_REFRESH                 1056
#define IDC_SEC_LIST                    1060
#define IDC_EDIT_DIR_EXA                1100
#define IDC_EDIT_DIR_EXS                1101
#define IDC_EDIT_DIR_IMA                1102
#define IDC_EDIT_DIR_IMS                1103
#define IDC_EDIT_DIR_RESA               1104
#define IDC_EDIT_DIR_RESS               1105
#define IDC_EDIT_DIR_EXCA               1106
#define IDC_EDIT_DIR_EXCS               1107
#define IDC_EDIT_DIR_SECA               1108
#define IDC_EDIT_DIR_SECS               1109
#define IDC_EDIT_DIR_RELA               1110
#define IDC_EDIT_DIR_RELS               1111
#define IDC_EDIT_DIR_DEBA               1112
#define IDC_EDIT_DIR_DEBS               1113
#define IDC_EDIT_DIR_ARCHA              1114
#define IDC_EDIT_DIR_ARCHS              1115
#define IDC_EDIT_DIR_GLOA               1116
#define IDC_EDIT_DIR_GLOS               1117
#define IDC_EDIT_DIR_TLSA               1118
#define IDC_EDIT_DIR_TLSS               1119
#define IDC_EDIT_DIR_LOADA              1120
#define IDC_EDIT_DIR_LOADS              1121
#define IDC_EDIT_DIR_BIMPA              1122
#define IDC_EDIT_DIR_BIMPS              1123
#define IDC_EDIT_DIR_IATA               1124
#define IDC_EDIT_DIR_IATS               1125
#define IDC_EDIT_DIR_DELA               1126
#define IDC_EDIT_DIR_DELS               1127
#define IDC_EDIT_DIR_COMA               1128
#define IDC_EDIT_DIR_COMS               1129
#define IDC_EDIT_DIR_RA                 1130
#define IDC_EDIT_DIR_RS                 1131
#define IDB_EDIT_DIR_REFRESH            1132
#define IDC_EDIT_DIR_EX_CHA             1133
#define IDC_EDIT_DIR_EX_TIME            1134
#define IDC_EDIT_DIR_EX_MAJ             1135
#define IDC_EDIT_DIR_EX_MIN             1136
#define IDC_EDIT_DIR_EX_NAMER           1137
#define IDC_EDIT_DIR_EX_BASE            1138
#define IDC_EDIT_DIR_EX_NOFUN           1139
#define IDC_EDIT_DIR_EX_NONAME          1140
#define IDC_EDIT_DIR_EX_ADFUN           1141
#define IDC_EDIT_DIR_EX_ADNAME          1142
#define IDC_EDIT_DIR_EX_ADORD           1143
#define IDC_EDIT_DIR_EX_NAMES           1144
#define IDC_EDIT_DIR_EX_LIST            1145
#define IDC_EDIT_DIR_IMPORT_FUNC        1146
#define IDC_EDIT_DIR_IMPORT_DLL         1147
#define IDC_CONV_RVA                    1147
#define IDC_CONV_FOA                    1148
#define IDB_CONV_CALC                   1149
#define IDB_BITMAP_DOS                  1149
#define IDC_CONV_MRVA                   1154
#define IDC_CONV_MFOA                   1155
#define IDC_SEC_CHECK1                  1158
#define IDC_SEC_CHECK2                  1159
#define IDC_SEC_CHECK3                  1160
#define IDC_SEC_CHECK4                  1161
#define IDC_SEC_CHECK13                 1162
#define IDC_SEC_CHECK5                  1165
#define IDC_SEC_CHECK7                  1166
#define IDC_SEC_CHECK6                  1167
#define IDC_SEC_CHECK8                  1168
#define IDC_SEC_CHECK9                  1169
#define IDC_SEC_CHECK11                 1170
#define IDC_SEC_CHECK10                 1171
#define IDC_SEC_CHECK12                 1172
#define IDC_TOOL_SEC_EDIT1              1173
#define IDC_TOOL_SEC_NAME               1173
#define IDC_TOOL_SEC_COMBO1             1174
#define IDC_TOOL_SEC_COMBO2             1175
#define IDB_TOOL_SEC_COMBINE            1176
#define IDC_TOOL_SEC_EDIT2              1177
#define IDC_TOOL_SEC_VSIZE              1177
#define IDC_TOOL_SEC_EDIT3              1178
#define IDC_TOOL_SEC_EDIT4              1179
#define IDC_TOOL_SEC_FSIZE              1179
#define IDC_TOOL_SEC_EDIT5              1180
#define IDC_TOOL_SEC_EDIT6              1181
#define IDC_TOOL_SEC_PRELOC             1181
#define IDB_TOOL_SEC_ADD                1182
#define IDC_TOOL_SEC_EDIT7              1184
#define IDC_TOOL_SEC_EDIT8              1185
#define IDC_TOOL_SEC_RELOCNUM           1185
#define IDC_TOOL_SEC_EDIT9              1186
#define IDC_TOOL_SEC_EDIT10             1187
#define IDC_TOOL_SEC_CHARA              1187
#define IDC_TOOL_SEC_BAR                1188
#define IDC_FILE_OPENPRO_PRO            1189
#define IDC_FILE_OPENPRO_MOD            1190
#define IDC_FILE_OPENPRO_OPEN           1191
#define IDC_TOOL_REMOTE_DLLNAME         1192
#define IDC_TOOL_REMOTE_PID             1193
#define IDB_TOOL_REMOTE_INJ             1194
#define IDC_TOOL_REMOTE_BAR             1195
#define ID_FILE_OPEN                    32771
#define ID_FILE_SAVE                    32772
#define ID_EDIT_IMAGE                   32773
#define ID_EDIT_IMAGE32774              32774
#define ID_EDIT_IMAGE32775              32775
#define ID_EDIT_IMAGE32776              32776
#define ID_EDIT_SECTION                 32777
#define ID_EDIT_IMPORTDIRECTORY         32778
#define ID_EDIT_EXPORTDIRECTORY         32779
#define ID_EDIT_RELOCATIONDIRECTORY     32780
#define ID_EDIT_COMBINESECTION          32781
#define ID_EDIT_ADDSECTION              32782
#define ID_EDIT_DOS                     32783
#define ID_EDIT_PE                      32784
#define ID_EDIT_OPTIONAL                32785
#define ID_EDIT_DIRECTORY               32786
#define IDM_EDIT_DOS                    32787
#define IDM_EDIT_PE                     32788
#define IDM_EDIT_OPTIONAL               32789
#define IDM_EDIT_DIRECTORY              32790
#define IDM_EDIT_SECTION                32791
#define IDM_EDIT_COMBINESECTION         32792
#define IDM_EDIT_ADDSECTION             32793
#define IDM_EDIT_IMPORTDIRECTORY        32794
#define IDM_EDIT_EXPORTDIRECTORY        32795
#define IDM_EDIT_RELOCATIONDIRECTORY    32796
#define IDM_FILE_OPEN                   32797
#define IDM_FILE_SAVE                   32798
#define IDM_EDIT_FILE                   32799
#define ID_TOOL_RVATOFOA                32800
#define IDM_TOOL_RVATOFOA               32801
#define IDM_TOOL_CONVERTER              32802
#define ID_TOOL_MANIPULATESECTION       32803
#define ID_TOOL_SECTION                 32804
#define IDM_TOOL_SECTION                32805
#define ID_FILE_OPENPROCESS             32806
#define ID_PROCESS_OPEN                 32807
#define IDM_PROCESS_OPEN                32808
#define ID_TOOL_REMOTETHREADINJECTION   32809
#define ID_TOOL_DLLINJECTION            32810
#define ID_TOOL_REMOTEINJ               32811
#define IDM_TOOL_REMOTEINJ              32812
#define IDM_TOOL_DLLINJ                 32813
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1196
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
